import { describe, expect, it } from 'vitest';
import { isGenerated, isMinified, transformFile } from '../src/engine/transform.js';

describe('minified and generated files', () => {
  const minified = `!function(e){${'var a=1,b=2;function c(d){return d*2}'.repeat(200)}}(window);\n`;

  it('detects minified code by line length, not by size', () => {
    expect(isMinified(minified)).toBe(true);
    expect(isMinified('x'.repeat(3000))).toBe(false); // too small to matter
    expect(isMinified(Array.from({ length: 400 }, (_, i) => `const v${i} = compute(${i});`).join('\n'))).toBe(false);
  });

  it('replaces minified files with a note, except in full mode', async () => {
    const skeleton = await transformFile('vendor/lib.min.js', minified, { mode: 'skeleton' });
    expect(skeleton).toMatchObject({ strategy: 'minified', language: { id: 'javascript' } });
    expect(skeleton.content).toBe(`[minified: 2 lines, ${minified.length} chars omitted]\n`);
    expect((await transformFile('vendor/lib.min.js', minified, { mode: 'full' })).content).toBe(minified);
    // Markdown paragraphs on one line are prose, not minified code.
    const prose = `# Guide\n\n${'A long paragraph of prose. '.repeat(300)}\n`;
    expect((await transformFile('docs/guide.md', prose, { mode: 'skeleton' })).strategy).not.toBe('minified');
  });

  it('outlines generated files in skeleton mode', async () => {
    const src = '// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n\ntype User struct {\n\tName string\n}\n\nfunc (x *User) GetName() string {\n\tif x != nil {\n\t\treturn x.Name\n\t}\n\treturn ""\n}\n';
    expect(isGenerated(src)).toBe(true);
    const result = await transformFile('user.pb.go', src, { mode: 'skeleton' });
    expect(result.strategy).toBe('outline');
    expect(result.content).toContain('func (x *User) GetName() string');
    expect(result.content).not.toContain('return x.Name');
  });

  it('does not mistake ordinary comments for generated-file markers', () => {
    expect(isGenerated('// IDs are generated by the server.\nexport const x = 1;\n')).toBe(false);
    expect(isGenerated('// Re-exports from the auto-generated protocol layer.\nexport * from "./p";\n')).toBe(false);
    expect(isGenerated('// AUTOGENERATED - do not edit.\nexport type T = string;\n')).toBe(true);
    expect(isGenerated('# Generated by the protocol buffer compiler.  DO NOT EDIT!\n')).toBe(true);
    expect(isGenerated('const note = "DO NOT EDIT";\n')).toBe(false);
    expect(isGenerated('# This file is automatically generated by Django.\nfrom django.db import migrations\n')).toBe(true);
    expect(isGenerated('/**\n * @generated SignedSource<<abc>>\n */\n')).toBe(true);
  });
});
